build:
    dependencies:
        before:
            - npm install
    tests:
        override:
            -
                command: 'npm run clover'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
checks:
    javascript: true
filter:
    excluded_paths:
        - "test"
